<Project Sdk="Microsoft.NET.Sdk.Web">

    <PropertyGroup>
        <TargetFramework>net7.0</TargetFramework>
        <Nullable>enable</Nullable>
        <ImplicitUsings>enable</ImplicitUsings>
        <DockerDefaultTargetOS>Windows</DockerDefaultTargetOS>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="Microsoft.AspNetCore.OpenApi" Version="7.0.16"/>
        <PackageReference Include="Swashbuckle.AspNetCore" Version="6.5.0"/>
    </ItemGroup>

    <ItemGroup>
      <Content Include="..\.dockerignore">
        <Link>.dockerignore</Link>
      </Content>
    </ItemGroup>

    <ItemGroup>
      <Folder Include="Api\" />
    </ItemGroup>

    <ItemGroup>
      <ProjectReference Include="..\CQRSAndMediatR\CQRSAndMediatR.csproj" />
      <ProjectReference Include="..\Repository\Repository.csproj" />
      <ProjectReference Include="..\Seed\Seed.csproj" />
      <ProjectReference Include="..\UseCases\UseCases.csproj" />
    </ItemGroup>

</Project>
